//! Braid group cryptography -- research stub for Anshel-Anshel-Goldfeld key exchange.
//!
//! This module defines algebraic data types and a trait for AAG key exchange
//! over braid groups. NO implementation is provided -- types only.
//!
//! Braid groups are non-abelian groups with generators sigma_1, ..., sigma_{n-1}
//! satisfying the braid relations. The conjugacy search problem in braid groups
//! is a candidate hard problem for post-quantum cryptography.
//!
//! References:
//!   Anshel, Anshel, Goldfeld -- "An algebraic method for public-key cryptography" (1999)
//!   Birman -- "Braids, Links, and Mapping Class Groups" (1974)

use crate::types::MorphResult;

// ---- Algebraic Data Types ----

/// A single braid generator -- either sigma_i or its inverse sigma_i^{-1}.
///
/// In the braid group B_n, generator sigma_i swaps strand i with strand i+1
/// (positive crossing), and SigmaInv(i) is the inverse crossing.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum BraidGenerator {
    /// Positive crossing: strand i over strand i+1
    Sigma(usize),
    /// Negative crossing: strand i+1 over strand i (inverse of Sigma)
    SigmaInv(usize),
}

/// A braid word -- a sequence of generators in the braid group B_n.
///
/// The word represents the product sigma_{g_1} * sigma_{g_2} * ... * sigma_{g_k}
/// where each g_i is either a positive or inverse generator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BraidWord {
    /// The sequence of generators forming this braid word
    pub generators: Vec<BraidGenerator>,
    /// The number of strands in the braid group (n in B_n)
    pub num_strands: usize,
}

/// Parameters for the Anshel-Anshel-Goldfeld protocol.
///
/// Defines the braid group and the public generator subsets for Alice and Bob.
#[derive(Debug, Clone)]
pub struct AagParams {
    /// Number of strands in B_n
    pub num_strands: usize,
    /// Alice's public generator set {a_1, ..., a_L1} -- elements of B_n
    pub alice_generators: Vec<BraidWord>,
    /// Bob's public generator set {b_1, ..., b_L2} -- elements of B_n
    pub bob_generators: Vec<BraidWord>,
}

/// Private key in the AAG protocol -- a secret word in the subgroup
/// generated by the party's public generators.
#[derive(Debug, Clone)]
pub struct AagPrivateKey {
    /// The secret word, an element of the subgroup <generators>
    pub secret_word: BraidWord,
}

/// Public key in the AAG protocol -- the conjugates of the other party's
/// generators by the secret word.
///
/// If Alice's secret is `a` and Bob's generators are {b_1, ..., b_L2},
/// then Alice publishes {a^{-1} b_1 a, ..., a^{-1} b_L2 a}.
#[derive(Debug, Clone)]
pub struct AagPublicKey {
    /// The conjugated generators: {s^{-1} g_i s} for each generator g_i
    pub conjugated_generators: Vec<BraidWord>,
}

/// Shared secret in the AAG protocol -- the commutator of Alice's and Bob's
/// secret words.
///
/// K = a^{-1} b^{-1} a b
///
/// Both parties can compute this independently from their private key
/// and the other party's public key.
#[derive(Debug, Clone)]
pub struct AagSharedSecret {
    /// The commutator braid word [a, b] = a^{-1} b^{-1} a b
    pub commutator: BraidWord,
}

// ---- Trait Definition ----

/// Trait for braid-based key exchange (Anshel-Anshel-Goldfeld protocol).
///
/// Implementors must provide the full AAG protocol:
/// 1. Parameter generation (choose braid group and generator sets)
/// 2. Private key generation (choose secret word in subgroup)
/// 3. Public key computation (conjugate other party's generators)
/// 4. Shared secret derivation (compute commutator)
pub trait BraidKeyExchange {
    /// Generate protocol parameters: braid group order and generator sets.
    ///
    /// Returns (params) where params contains the braid group B_n
    /// and the public generator subsets for both parties.
    fn generate_params(security_level: usize) -> MorphResult<AagParams>;

    /// Generate a private key -- a secret word in the subgroup generated
    /// by the party's public generators.
    ///
    /// The secret word should be sufficiently long and random to resist
    /// length-based attacks.
    fn generate_private_key(
        params: &AagParams,
        is_alice: bool,
    ) -> MorphResult<AagPrivateKey>;

    /// Compute the public key by conjugating the other party's generators
    /// with the secret word.
    ///
    /// If is_alice: publishes {a^{-1} b_i a} for each of Bob's generators b_i
    /// If is_bob:   publishes {b^{-1} a_i b} for each of Alice's generators a_i
    fn compute_public_key(
        params: &AagParams,
        private_key: &AagPrivateKey,
        is_alice: bool,
    ) -> MorphResult<AagPublicKey>;

    /// Derive the shared secret from own private key and other party's public key.
    ///
    /// Both parties compute K = a^{-1} b^{-1} a b (the commutator).
    /// Alice reconstructs b from Bob's public key; Bob reconstructs a from Alice's.
    fn derive_shared_secret(
        private_key: &AagPrivateKey,
        other_public_key: &AagPublicKey,
        params: &AagParams,
        is_alice: bool,
    ) -> MorphResult<AagSharedSecret>;
}
